name: 🎞️ GIF to ASCII

on:
  push:
    paths:
      - "tenor.gif"
      - "gif_to_ascii.py"
      - ".github/workflows/ascii.yml"

  workflow_dispatch:

jobs:
  convert:

    runs-on: ubuntu-latest

    steps:

      - name: 📥 Скачать репозиторий
        uses: actions/checkout@v4

      - name: 🐍 Установить Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: 📦 Установить библиотеки
        run: |
          pip install pillow numpy

      - name: 🎞️ Конвертировать GIF
        run: |
          python gif_to_ascii.py

      - name: 💾 Сохранить результат
        run: |

          git config --global user.name "github-actions[bot]"

          git config --global user.email \
            "41898282+github-actions[bot]@users.noreply.github.com"

          git add ascii.gif

          git diff --cached --quiet || \
            git commit -m "🤖 Update ASCII animation"

          git push
